Update asset_size_check.yml

diff --git a/.github/workflows/asset_size_check.yml b/.github/workflows/asset_size_check.yml
--- a/.github/workflows/asset_size_check.yml
+++ b/.github/workflows/asset_size_check.yml
@@ -44,24 +44,27 @@ jobs:
           if [ "$file_size" -gt 100 ]; then
             echo "$file | $file_size | $encoded_url | FAILED ❌" >> file_table.md
             has_exceeded_limit=1
-            echo "exceeded"
           else
             echo "$file | $file_size | $encoded_url | PASSED ✅" >> file_table.md
           fi
         done
-        echo "$(cat file_table.md)"
+        #echo "$(cat file_table.md)"
         if [ $has_exceeded_limit -eq 1 ]; then
-          table_output=$(cat file_table.md)
-          echo "$table_output"
-          echo "table_output<<EOF" >> $GITHUB_ENV
-          echo "$table_output" >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
+          #table_output=$(cat file_table.md)
+          #echo "$table_output"
+          #echo "table_output<<EOF" >> $GITHUB_ENV
+          #echo "$table_output" >> $GITHUB_ENV
+          #echo "EOF" >> $GITHUB_ENV
+          echo "We have encoutered few asset size above thresshold. please compress them"
+          echo -e "::error::$(cat file_table.md)"
+          exit 1;
           #echo check_status=1 >> $GITHUB_OUTPUT
         else
           exit 0;
         fi
     - name: Comment on PR
       uses: actions/github-script@v4
+      continue-on-error: true
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         script: |
